name: Scrape documentation for search engine

on:
  push:
    # branches: [ 'master' ]
    tags: [ 'v*.*.*' ]

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST "${{ secrets.TRIGGER_DOC_SCRAPING }}&delay=300"

